version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build: ./apache-php
    container_name: apache_php
    ports:
      - "8088:80"  # Si 80 está libre, puedes poner 80:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # Cambiado a 8081 en el host


volumes:
  db_data:
